on: push
jobs:
  ollama:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Run model
        uses: ai-action/ollama-action@v1
        id: model
        with:
          model: qwen2.5-coder:14b
          prompt: Explain the basics of machine learning.

      - name: Print response
        run: echo "$response"
        env:
          response: ${{ steps.model.outputs.response }}
